INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (004, 0093, "AF", "AFG", "Afghanistan", "Islamic Republic of Afghanistan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (008, 0355, "AL", "ALB", "Albania", "Republic of Albania");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (012, 0213, "DZ", "DZA", "Algeria", "People's Democratic Republic of Algeria");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (016, 0684, "AS", "ASM", "American Samoa", "Territory of American Samoa");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (020, 0376, "AD", "AND", "Andorra", "Principality of Andorra");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (024, 0244, "AO", "AGO", "Angola", "Republic of Angola");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (660, 1264, "AI", "AIA", "Anguilla", "Anguilla");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (010, 0672, "AQ", "ATA", "Antarctica", "Antarctica");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (028, 1268, "AG", "ATG", "Antigua and Barbuda", "Antigua and Barbuda");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (032, 0054, "AR", "ARG", "Argentina", "Argentine Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (051, 0374, "AM", "ARM", "Armenia", "Republic of Armenia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (533, 0297, "AW", "ABW", "Aruba", "Aruba");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (036, 0061, "AU", "AUS", "Australia", "Commonwealth of Australia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (040, 0043, "AT", "AUT", "Austria", "Republic of Austria");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (031, 0994, "AZ", "AZE", "Azerbaijan", "Republic of Azerbaijan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (044, 1242, "BS", "BHS", "Bahamas", "Commonwealth of the Bahamas");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (048, 0973, "BH", "BHR", "Bahrain", "Kingdom of Bahrain");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (050, 0880, "BD", "BGD", "Bangladesh", "People's Republic of Bangladesh");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (052, 0246, "BB", "BRB", "Barbados", "Barbados");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (112, 0375, "BY", "BLR", "Belarus", "Republic of Belarus");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (056, 0032, "BE", "BEL", "Belgium", "Kingdom of Belgium");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (084, 0501, "BZ", "BLZ", "Belize", "Belize");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (204, 0229, "BJ", "BEN", "Benin", "Republic of Benin");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (060, 1441, "BM", "BMU", "Bermuda", "Bermuda");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (064, 0975, "BT", "BTN", "Bhutan", "Kingdom of Bhutan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (068, 0591, "BO", "BOL", "Bolivia", "Plurinational State of Bolivia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (070, 0387, "BA", "BIH", "Bosnia and Herzegovina", "Bosnia and Herzegovina");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (072, 0267, "BW", "BWA", "Botswana", "Republic of Botswana");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (074, 0047, "BV", "BVT", "Bouvet Island", "Bouvet Island");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (076, 0055, "BR", "BRA", "Brazil", "Federative Republic of Brazil");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (086, 0246, "IO", "IOT", "British Indian Ocean Territory", "British Indian Ocean Territory");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (096, 0673, "BN", "BRN", "Brunei Darussalam", "Nation of Brunei, Abode of Peace");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (100, 0359, "BG", "BGR", "Bulgaria", "Republic of Bulgaria");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (854, 0226, "BF", "BFA", "Burkina Faso", "Burkina Faso");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (108, 0257, "BI", "BDI", "Burundi", "Republic of Burundi");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (116, 0855, "KH", "KHM", "Cambodia", "Kingdom of Cambodia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (120, 0237, "CM", "CMR", "Cameroon", "Republic of Cameroon");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (124, 0001, "CA", "CAN", "Canada", "Canada");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (132, 0238, "CV", "CPV", "Cape Verde", "Republic of Cabo Verde");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (136, 1345, "KY", "CYM", "Cayman Islands", "Cayman Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (140, 0236, "CF", "CAF", "Central African Republic", "Central African Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (148, 0235, "TD", "TCD", "Chad", "Republic of Chad");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (152, 0056, "CL", "CHL", "Chile", "Republic of Chile");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (156, 0086, "CN", "CHN", "China", "People's Republic of China");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (162, 0061, "CX", "CXR", "Christmas Island", "Territory of Christmas Island");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (166, 0672, "CC", "CCK", "Cocos (Keeling) Islands", "Territory of the Cocos (Keeling) Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (170, 0057, "CO", "COL", "Colombia", "Republic of Colombia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (174, 0269, "KM", "COM", "Comoros", "Union of the Comoros");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (178, 0242, "CG", "COG", "Congo", "Republic of the Congo");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (180, 0242, "CD", "COD", "Congo (DR)", "Democratic Republic of the Congo");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (184, 0682, "CK", "COK", "Cook Islands", "Cook Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (188, 0506, "CR", "CRI", "Costa Rica", "Republic of Costa Rica");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (384, 0225, "CI", "CIV", "Cote D'Ivoire", "Republic of Côte d'Ivoire");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (191, 0385, "HR", "HRV", "Croatia", "Republic of Croatia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (192, 0053, "CU", "CUB", "Cuba", "Republic of Cuba");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (196, 0357, "CY", "CYP", "Cyprus", "Republic of Cyprus");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (203, 0420, "CZ", "CZE", "Czech Republic", "Czech Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (208, 0045, "DK", "DNK", "Denmark", "Kingdom of Denmark");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (262, 0253, "DJ", "DJI", "Djibouti", "Republic of Djibouti");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (212, 1767, "DM", "DMA", "Dominica", "Commonwealth of Dominica");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (214, 1809, "DO", "DOM", "Dominican Republic", "Dominican Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (818, 0020, "EG", "EGY", "Egypt", "Arab Republic of Egypt");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (222, 0503, "SV", "SLV", "El Salvador", "Republic of El Salvador");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (226, 0240, "GQ", "GNQ", "Equatorial Guinea", "Republic of Equatorial Guinea");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (232, 0291, "ER", "ERI", "Eritrea", "State of Eritrea");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (233, 0372, "EE", "EST", "Estonia", "Republic of Estonia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (231, 0251, "ET", "ETH", "Ethiopia", "Federal Democratic Republic of Ethiopia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (238, 0500, "FK", "FLK", "Falkland Islands (Malvinas)", "Falkland Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (234, 0298, "FO", "FRO", "Faroe Islands", "Faroe Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (242, 0679, "FJ", "FJI", "Fiji", "Republic of Fiji");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (246, 0358, "FI", "FIN", "Finland", "Republic of Finland");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (250, 0033, "FR", "FRA", "France", "French Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (254, 0594, "GF", "GUF", "French Guiana", "French Guiana");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (258, 0689, "PF", "PYF", "French Polynesia", "French Polynesia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (260, 0033, "TF", "ATF", "French Southern Territories", "French Southern Territories");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (266, 0241, "GA", "GAB", "Gabon", "Gabonese Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (270, 0220, "GM", "GMB", "Gambia", "Republic of the Gambia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (268, 0995, "GE", "GEO", "Georgia", "Georgia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (276, 0049, "DE", "DEU", "Germany", "Federal Republic of Germany");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (288, 0233, "GH", "GHA", "Ghana", "Republic of Ghana");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (292, 0350, "GI", "GIB", "Gibraltar", "Gibraltar");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (300, 0030, "GR", "GRC", "Greece", "Hellenic Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (304, 0299, "GL", "GRL", "Greenland", "Greenland");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (308, 1473, "GD", "GRD", "Grenada", "Grenada");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (312, 0590, "GP", "GLP", "Guadeloupe", "Guadeloupe");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (316, 1671, "GU", "GUM", "Guam", "Territory of Guam");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (320, 0502, "GT", "GTM", "Guatemala", "Republic of Guatemala");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (324, 0224, "GN", "GIN", "Guinea", "Republic of Guinea");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (624, 0245, "GW", "GNB", "Guinea-Bissau", "Republic of Guinea-Bissau");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (328, 0592, "GY", "GUY", "Guyana", "Co-operative Republic of Guyana");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (332, 0509, "HT", "HTI", "Haiti", "Republic of Haiti");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (334, 0672, "HM", "HMD", "Heard Island and Mcdonald Islands", "Territory of Heard Island and McDonald Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (336, 0039, "VA", "VAT", "Vatican City", "Vatican City State");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (340, 0504, "HN", "HND", "Honduras", "Republic of Honduras");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (344, 0852, "HK", "HKG", "Hong Kong", "Hong Kong Special Administrative Region of the People's Republic of China");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (348, 0036, "HU", "HUN", "Hungary", "Hungary");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (352, 0354, "IS", "ISL", "Iceland", "Iceland");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (356, 0091, "IN", "IND", "India", "Republic of India");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (360, 0062, "ID", "IDN", "Indonesia", "Republic of Indonesia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (364, 0098, "IR", "IRN", "Iran", "Islamic Republic of Iran");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (368, 0964, "IQ", "IRQ", "Iraq", "Republic of Iraq");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (372, 0353, "IE", "IRL", "Ireland", "Ireland");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (376, 0972, "IL", "ISR", "Israel", "State of Israel");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (380, 0039, "IT", "ITA", "Italy", "Italian Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (388, 1876, "JM", "JAM", "Jamaica", "Jamaica");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (392, 0081, "JP", "JPN", "Japan", "Japan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (400, 0962, "JO", "JOR", "Jordan", "Hashemite Kingdom of Jordan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (398, 0007, "KZ", "KAZ", "Kazakhstan", "Republic of Kazakhstan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (404, 0254, "KE", "KEN", "Kenya", "Republic of Kenya");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (296, 0686, "KI", "KIR", "Kiribati", "Republic of Kiribati");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (408, 0850, "KP", "PRK", "North Korea", "Democratic People's Republic of Korea");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (410, 0082, "KR", "KOR", "South Korea", "Republic of Korea");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (414, 0965, "KW", "KWT", "Kuwait", "State of Kuwait");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (417, 0996, "KG", "KGZ", "Kyrgyzstan", "Kyrgyz Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (418, 0856, "LA", "LAO", "Laos", "Lao People's Democratic Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (428, 0371, "LV", "LVA", "Latvia", "Republic of Latvia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (422, 0961, "LB", "LBN", "Lebanon", "Lebanese Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (426, 0266, "LS", "LSO", "Lesotho", "Kingdom of Lesotho");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (430, 0231, "LR", "LBR", "Liberia", "Republic of Liberia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (434, 0218, "LY", "LBY", "Libya", "Libya");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (438, 0423, "LI", "LIE", "Liechtenstein", "Principality of Liechtenstein");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (440, 0370, "LT", "LTU", "Lithuania", "Republic of Lithuania");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (442, 0352, "LU", "LUX", "Luxembourg", "Grand Duchy of Luxembourg");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (446, 0853, "MO", "MAC", "Macao", "Macao");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (807, 0389, "MK", "MKD", "Macedonia", "Republic of Macedonia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (450, 0261, "MG", "MDG", "Madagascar", "Republic of Madagascar");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (454, 0265, "MW", "MWI", "Malawi", "Republic of Malawi");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (458, 0060, "MY", "MYS", "Malaysia", "Malaysia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (462, 0960, "MV", "MDV", "Maldives", "Republic of Maldives");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (466, 0223, "ML", "MLI", "Mali", "Republic of Mali");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (470, 0356, "MT", "MLT", "Malta", "Republic of Malta");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (584, 0692, "MH", "MHL", "Marshall Islands", "Republic of the Marshall Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (474, 0596, "MQ", "MTQ", "Martinique", "Martinique");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (478, 0222, "MR", "MRT", "Mauritania", "Islamic Republic of Mauritania");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (480, 0230, "MU", "MUS", "Mauritius", "Republic of Mauritius");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (175, 0269, "YT", "MYT", "Mayotte", "Department of Mayotte");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (484, 0052, "MX", "MEX", "Mexico", "United Mexican States");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (583, 0691, "FM", "FSM", "Micronesia", "Federated States of Micronesia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (498, 0373, "MD", "MDA", "Moldova", "Republic of Moldova");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (492, 0377, "MC", "MCO", "Monaco", "Principality of Monaco");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (496, 0976, "MN", "MNG", "Mongolia", "Mongolia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (500, 1664, "MS", "MSR", "Montserrat", "Montserrat");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (504, 0212, "MA", "MAR", "Morocco", "Kingdom of Morocco");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (508, 0258, "MZ", "MOZ", "Mozambique", "Republic of Mozambique");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (104, 0095, "MM", "MMR", "Myanmar", "Republic of the Union of Myanmar");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (516, 0264, "NA", "NAM", "Namibia", "Republic of Namibia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (520, 0674, "NR", "NRU", "Nauru", "Republic of Nauru");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (524, 0977, "NP", "NPL", "Nepal", "Federal Democratic Republic of Nepal");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (528, 0031, "NL", "NLD", "Netherlands", "Netherlands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (530, 0599, "AN", "ANT", "Netherlands Antilles", "Netherlands Antilles");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (540, 0687, "NC", "NCL", "New Caledonia", "New Caledonia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (554, 0064, "NZ", "NZL", "New Zealand", "New Zealand");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (558, 0505, "NI", "NIC", "Nicaragua", "Republic of Nicaragua");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (562, 0227, "NE", "NER", "Niger", "Republic of Niger");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (566, 0234, "NG", "NGA", "Nigeria", "Federal Republic of Nigeria");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (570, 0683, "NU", "NIU", "Niue", "Niue");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (574, 0672, "NF", "NFK", "Norfolk Island", "Territory of Norfolk Island");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (580, 1670, "MP", "MNP", "Northern Mariana Islands", "Commonwealth of the Northern Mariana Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (578, 0047, "NO", "NOR", "Norway", "Kingdom of Norway");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (512, 0968, "OM", "OMN", "Oman", "Sultanate of Oman");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (586, 0092, "PK", "PAK", "Pakistan", "Islamic Republic of Pakistan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (585, 0680, "PW", "PLW", "Palau", "Republic of Palau");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (275, 0970, "PS", "PSE", "Palestine", "State of Palestine");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (591, 0507, "PA", "PAN", "Panama", "Republic of Panama");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (598, 0675, "PG", "PNG", "Papua New Guinea", "Independent State of Papua New Guinea");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (600, 0595, "PY", "PRY", "Paraguay", "Republic of Paraguay");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (604, 0051, "PE", "PER", "Peru", "Republic of Peru");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (608, 0063, "PH", "PHL", "Philippines", "Republic of the Philippines");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (612, 0672, "PN", "PCN", "Pitcairn Islands", "Pitcairn");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (616, 0048, "PL", "POL", "Poland", "Republic of Poland");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (620, 0351, "PT", "PRT", "Portugal", "Portuguese Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (630, 1787, "PR", "PRI", "Puerto Rico", "Commonwealth of Puerto Rico");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (634, 0974, "QA", "QAT", "Qatar", "State of Qatar");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (638, 0262, "RE", "REU", "Réunion", "Réunion");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (642, 0040, "RO", "ROM", "Romania", "Romania");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (643, 0070, "RU", "RUS", "Russia", "Russian Federation");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (646, 0250, "RW", "RWA", "Rwanda", "Republic of Rwanda");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (654, 0290, "SH", "SHN", "Saint Helena", "Saint Helena");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (659, 1869, "KN", "KNA", "Saint Kitts", "State of Saint Kitts");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (662, 1758, "LC", "LCA", "Saint Lucia", "Saint Lucia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (666, 0508, "PM", "SPM", "Saint Pierre and Miquelon", "Saint Pierre and Miquelon");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (670, 1784, "VC", "VCT", "Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (882, 0684, "WS", "WSM", "Samoa", "Independent State of Samoa");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (674, 0378, "SM", "SMR", "San Marino", "Republic of San Marino");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (678, 0239, "ST", "STP", "Sao Tome and Principe", "Democratic Republic of São Tomé and Príncipe");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (682, 0966, "SA", "SAU", "Saudi Arabia", "Kingdom of Saudi Arabia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (686, 0221, "SN", "SEN", "Senegal", "Republic of Senegal");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (688, 0381, "CS", "SRB", "Serbia and Montenegro", "State Union of Serbia and Montenegro");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (690, 0248, "SC", "SYC", "Seychelles", "Republic of Seychelles");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (694, 0232, "SL", "SLE", "Sierra Leone", "Republic of Sierra Leone");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (702, 0065, "SG", "SGP", "Singapore", "Republic of Singapore");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (703, 0421, "SK", "SVK", "Slovakia", "Slovak Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (705, 0386, "SI", "SVN", "Slovenia", "Republic of Slovenia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (090, 0677, "SB", "SLB", "Solomon Islands", "Solomon Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (706, 0252, "SO", "SOM", "Somalia", "Federal Republic of Somalia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (710, 0027, "ZA", "ZAF", "South Africa", "Republic of South Africa");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (239, 0500, "GS", "SGS", "South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (724, 0034, "ES", "ESP", "Spain", "Kingdom of Spain");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (144, 0094, "LK", "LKA", "Sri Lanka", "Democratic Socialist Republic of Sri Lanka");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (736, 0249, "SD", "SDN", "Sudan", "Republic of the Sudan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (740, 0597, "SR", "SUR", "Suriname", "Republic of Suriname");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (744, 0047, "SJ", "SJM", "Svalbard", "Svalbard");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (748, 0268, "SZ", "SWZ", "Swaziland", "Kingdom of Swaziland");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (752, 0046, "SE", "SWE", "Sweden", "Kingdom of Sweden");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (756, 0041, "CH", "CHE", "Switzerland", "Swiss Confederation");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (760, 0963, "SY", "SYR", "Syria", "Syrian Arab Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (158, 0886, "TW", "TWN", "Taiwan", "Taiwan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (762, 0992, "TJ", "TJK", "Tajikistan", "Republic of Tajikistan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (834, 0255, "TZ", "TZA", "Tanzania", "United Republic of Tanzania");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (764, 0066, "TH", "THA", "Thailand", "Kingdom of Thailand");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (626, 0670, "TL", "TLS", "East Timor", "Democratic Republic of Timor-Leste");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (768, 0228, "TG", "TGO", "Togo", "Togolese Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (772, 0690, "TK", "TKL", "Tokelau", "Tokelau");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (776, 0676, "TO", "TON", "Tonga", "Kingdom of Tonga");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (780, 1868, "TT", "TTO", "Trinidad and Tobago", "Republic of Trinidad and Tobago");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (788, 0216, "TN", "TUN", "Tunisia", "Tunisian Republic");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (792, 0090, "TR", "TUR", "Turkey", "Republic of Turkey");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (795, 7370, "TM", "TKM", "Turkmenistan", "Turkmenistan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (796, 1649, "TC", "TCA", "Turks and Caicos Islands", "Turks and Caicos Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (798, 0688, "TV", "TUV", "Tuvalu", "Tuvalu");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (800, 0256, "UG", "UGA", "Uganda", "Republic of Uganda");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (804, 0380, "UA", "UKR", "Ukraine", "Ukraine");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (784, 0971, "AE", "ARE", "United Arab Emirates", "United Arab Emirates");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (826, 0044, "GB", "GBR", "United Kingdom", "United Kingdom of Great Britain and Northern Ireland");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (840, 0001, "US", "USA", "United States", "United States of America");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (581, 0001, "UM", "UMI", "United States Minor Outlying Islands", "United States Minor Outlying Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (858, 0598, "UY", "URY", "Uruguay", "Eastern Republic of Uruguay");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (860, 0998, "UZ", "UZB", "Uzbekistan", "Republic of Uzbekistan");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (548, 0678, "VU", "VUT", "Vanuatu", "Republic of Vanuatu");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (862, 0058, "VE", "VEN", "Venezuela", "Bolivarian Republic of Venezuela");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (704, 0084, "VN", "VNM", "Vietnam", "Socialist Republic of Vietnam");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (092, 1284, "VG", "VGB", "Virgin Islands (British)", "Virgin Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (850, 1340, "VI", "VIR", "Virgin Islands (USA)", "Virgin Islands of the United States");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (876, 0681, "WF", "WLF", "Wallis and Futuna", "Territory of the Wallis and Futuna Islands");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (732, 0212, "EH", "ESH", "Western Sahara", "Western Sahara");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (887, 0967, "YE", "YEM", "Yemen", "Republic of Yemen");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (894, 0260, "ZM", "ZMB", "Zambia", "Republic of Zambia");
INSERT INTO COUNTRY (code, phone, iso, iso3, name, officialName) VALUES (716, 0263, "ZW", "ZWE", "Zimbabwe", "Republic of Zimbabwe");